### ISSUE TITLE
Export types

### ISSUE THREAD

**Issue by moltar** [ozum/pg-test-util#3]
I think it'd be useful to export some internal types.

E.g. `Database` type.

```ts
let database: Database
beforeEach(() => {
  database = await pgTestUtil.createDatabase()
})
```

Right now only the `PgTestUtil` class is exported.

Thanks.

**Comment by ozum** [comment]
Thanks. Yes that's right. Actually other types are needed as a chain. I exported most of the types in latest update. If you see a missing type please post.
