### ISSUE TITLE
Default for "to" in copyDatabase

### ISSUE THREAD

**Issue by moltar** [ozum/pg-test-util#4]
I think this could be a useful feature to have a default for `to` prop, which would default to the value of `pgTestUtil.generateName()`.

That way you can just create a new copy, without having to specify a name.

Alternatively, maybe create a `cloneDatabase` method that only takes in `from` argument and creates an automatic clone.

Right now I do this:

```ts
    const database = await pgTestUtil.copyDatabase({
      from: template,
      to: pgTestUtil.generateName(),
    })
```

But would be good to have:

```ts
    const database = await pgTestUtil.copyDatabase({
      from: template,

      // don't need to specify
      // to: pgTestUtil.generateName(),
    })
```

**Comment by ozum** [comment]
It's nice to have. I added it.

**Comment by moltar** [comment]
Thanks! :)
